import {Callback_Factory} from "../callback_factory.slint";
import { AboutSlint } from "std-widgets.slint";
export component Page_About inherits Rectangle {
    callback open_url(string);

    width: 100%;
    height: 100%;
    background: @linear-gradient(180deg, #5c6175 0%, #080114 100%);

    Image {
        source: @image-url("../images/phoenix.svg");
        image-fit: contain;
        width: 1200px;
        height: 1200px;
        x: (parent.width - self.width) / 2 -80px; 
        y: (parent.height - self.height) / 2 - 130px; 
    }

    Image{
        source: @image-url("../images/R.svg");
        image-fit: contain;
        width: 1000px;
        height: 1000px;
        x: (parent.width - self.width) / 2 + 80px; 
        y: (parent.height - self.height) / 2 - 115px;
    }


    Text { 
        text: "关于 RoboMaster Client v0.1 "; 
        color: area_client.has-hover ? #4da6ff : white;
        font-size: Callback-Factory.font_size*1px; 
        x: (parent.width - self.width) / 2;
        y: (parent.height) / 2 + 3px;

        area_client := TouchArea {
            width: 100%;
            height: 100%;
            mouse-cursor: pointer; // 鼠标变成手型
            clicked => {
                // 触发回调，传递 URL
                Callback_Factory.open-url("https://github.com/SillyBeee/Robomaster_Phoenix_Custom_Client");
            }
        }
    }


    AboutSlint {
        x: (parent.width - self.width) / 2;
        y: (parent.height) / 2 + 60px;
        width: 300px;
        height: 90px;
    }


    Text { 
        text: " Copyright (c) 2025 HDU—PHOENIX "; 
        color:  area_phoenix.has-hover ? #4da6ff : white;
        font-size: Callback-Factory.font_size*1px;
        x: (parent.width - self.width) / 2;
        y: (parent.height) / 2 + 30px;
        area_phoenix := TouchArea {
            width: 100%;
            height: 100%;
            mouse-cursor: pointer; // 鼠标变成手型
            clicked => {
                // 触发回调，传递 URL
                Callback_Factory.open-url("https://github.com/HDU-PHOENIX");
            }
        }
    }


    
    
}