import { Base_Component, ComponentProps } from "base_component.slint";
import { HealthBar} from "std_components/health_bar.slint"; 
import { Callback_Factory } from "../callback_factory.slint";
import { Coordinate-3D } from "std_components/coordinate.slint";
import { Sight } from "std_components/sight.slint";
export component Component_Render inherits Rectangle {
    width: 100%;
    height: 100%;
    background: transparent;
    clip: true;

    for comp[i] in Callback_Factory.components: Base_Component {
        // 1. 统一管理定位和交互 (Base_Component)
        props: {
            container_width: root.width,
            container_height: root.height,
            container_index: i,
            rel_x: comp.rel_x,
            rel_y: comp.rel_y,
            rel_width: comp.rel_width,
            rel_height: comp.rel_height,
            background_color: comp.color,       
            opacity_value: comp.opacity,
            layer: comp.layer,
        };
        
        is_selected: i == Callback_Factory.current_component_index;

        // 2. 根据类型填充内容 (@children)
        
        // 类型 A: 基础组件 (纯色块)
        if (comp.type == "base" || comp.type == "") : Rectangle {
            width: 100%;
            height: 100%;
            background: comp.color;
            opacity: comp.opacity;
        }

        // 类型 B: 血条组件 (内容)
        if (comp.type == "health_bar") : HealthBar {
            // 只需要传数据，不需要管定位
            props: parent.props; // 这里的 parent 是 Base_Component
            is_selected: parent.is_selected;
            // current_hp: ...
        }

        // 类型 C: 坐标系组件
        if (comp.type == "coordinate") : Coordinate-3D {
            props: parent.props;
            is_selected: parent.is_selected;
        }

        // 类型 D: 准心组件
        if (comp.type == "sight") : Sight {
            props: parent.props;
            is_selected: parent.is_selected;
        }


    }
}