import { VerticalBox, ComboBox, CheckBox } from "std-widgets.slint";
import { Callback_Factory } from "../../callback_factory.slint";

export component Page_Setting inherits Rectangle {
    // width: 100%;
    height: 100%;
    background: @linear-gradient(180deg, #5c6175 0%, #080114 100%);

    VerticalBox {
        alignment: start;
        padding: 20px;
        ComboBox {
            width: 200px;
            height: 30px;
            model: [ "860x540","1600x900", "1920x1080", "2560x1440", "2560x1600", "3840x2160" ];
            current-index: Callback_Factory.current-resolution-index;
            selected(current-value) => {
                Callback_Factory.set_resolution(current-value);
                Callback_Factory.current-resolution-index = self.current-index;
            }
        }

        CheckBox {
            x: 20px;
            // y: 100px;
            text: "全屏模式";
            checked: Callback_Factory.is_fullscreen;
            toggled() => {
                Callback_Factory.set_fullscreen(self.checked);
                Callback_Factory.is_fullscreen = self.checked;
            }
        }
    }
    
   
    
    
}