import { Base_Component } from "../../components/base_component.slint";
import { Slider, SpinBox } from "std-widgets.slint";
import { Callback_Factory } from "../../callback_factory.slint";
import { Component_Render } from "../../components/component_render.slint";
import { Attribute_Bar } from "./attribute_bar.slint";
export component Page_Design inherits Rectangle {
    width: 100%;
    height: 100%;
    background: @linear-gradient(180deg, #5c6175 0%, #080114 100%);


    GridLayout {
        spacing: 12px;
        padding: 16px;

        // 画布区域
        Rectangle {
            background: #0d0f1a;
            border-width: 1px;
            border-color: #303344;
            Component_Render {}
            width: 77%;
            height: 100%;
        }

        // 属性面板
        Attribute_Bar {
            // visible: self.has_selection;
            width: 21%;
            height: 100%;
        }
    }
}
