import {SideBar} from "side_bar.slint";
import {TabView} from "tab_view.slint";
import {  Callback-Factory } from "../callback_factory.slint";
export component MainMenu inherits Rectangle {
    width: 100%;
    height: 100%;
    background: white;

    tabview := TabView {
        x: sidebar.width;
        y: 0px;
        width: parent.width - sidebar.width;
        height: parent.height;
    }

    sidebar := SideBar {
        x: 0px;
        y: 0px;
    }
}

