import { VerticalBox } from "std-widgets.slint";
import { Callback_Factory } from "../callback_factory.slint";

component SideBarItem inherits Rectangle {
    in property <string> text;
    in property <image> icon: @image-url("images/default_icon.png");
    in property <bool> show_text: false;
    in property <bool> selected: Callback-Factory.current-index == self.index;
    in property <int> index: 0;
    
    
    width: 100%;
    height: 8%; 
    
    background: area.has-hover ? 
        @linear-gradient(90deg, #ffffff25 0%, #ffffff05 100%) : // 悬停时：左侧亮一点，向右渐隐
        (selected ? #ffffff15 : transparent);  

    border-radius: 8px;
    animate background { duration: 200ms; }
    
    area := TouchArea {
        width: 100%;
        height: 100%;
        clicked => {
            if(index!=-1){
                Callback-Factory.current-index = root.index;
            }
        }
    }

    HorizontalLayout {
        padding-left: parent.width * 0.05;
        padding-right: parent.width * 0.05;
        spacing: parent.width * 0.05;

        Image {
            source: root.icon;
            image-fit: contain;
            vertical-alignment: center;
            height: 60%;
            width: Callback_Factory.font_size * 2px;
        }

        Text {
            visible: root.show_text;
            text: root.text;
            color: white;
            vertical-alignment: center;
            font-size: Callback-Factory.font_size*1px;
            overflow: elide;
        }
    }
}

export component SideBar inherits Rectangle {
    out property <length> collapsed-width: Callback_Factory.font_size * 3.5px;
    out property <length> expanded-width: Callback_Factory.font_size * 15px;
    out property <bool> is_expanded: false;

    height: 100%;
    background: @linear-gradient(180deg, #24293c 0%, #1a1a1a 100%);
    clip: true; 
    

    

    width: is_expanded ? expanded-width : collapsed-width;

    animate width { duration: 300ms; easing: ease-out-quart; }

    drop-shadow-blur: 10px;
    drop-shadow-color: #00000080;
    drop-shadow-offset-x: 2px;

    VerticalBox {
        padding: 10px;
        padding-top: 20px;
        spacing: 10px;
        z: 1; // 放在上层
        
        item-menu := SideBarItem {
            icon: @image-url("../icons/open.svg");
            text: "主菜单";
            index: -1; 
            show_text: root.is_expanded;
            TouchArea {
                width: 100%;
                height: 100%;
                clicked => {
                    root.is_expanded = !root.is_expanded;
                }
            }
        }


        item-dashboard := SideBarItem {
            icon: @image-url("../icons/dashboard.svg");
            text: "Dashboard";
            index: 0;
            show_text: root.is_expanded;
            
        }
        
        item-design := SideBarItem {
            icon: @image-url("../icons/design.svg");
            text: "Design";
            index: 1;
            show_text: root.is_expanded;
        }

        item-settings := SideBarItem {
            icon: @image-url("../icons/setting.svg");
            text: "Settings";
            index: 2;
            show_text: root.is_expanded;
        }
        
        Rectangle { vertical-stretch: 1; }

        item-about := SideBarItem {
            icon: @image-url("../icons/about.svg");
            text: "About";
            index: 3;
            show_text: root.is_expanded;
        }
    }
}