import { VerticalBox } from "std-widgets.slint";
import { Page_Setting } from "../pages/page_setting/page_setting.slint";
import { Page_DashBoard } from "../pages/page_dashboard/page_dashboard.slint";
import { Page_About } from "../pages/page_about/page_about.slint";
import { Page_Design } from "../pages/page_design/page_design.slint";
import { Callback_Factory, Callback-Factory } from "../callback_factory.slint";

export component TabView inherits Rectangle {

    if Callback-Factory.current-index == 0 : Page_DashBoard {}

    if Callback-Factory.current-index == 1 : Page_Design {}


    if Callback-Factory.current-index == 2 : Page_Setting {}


    if Callback-Factory.current-index == 3 : Page_About {}
}

