import {
    Pose_slint,
    GameStatus_slint,
    GlobalUnitStatus_slint,
    RobotDynamicStatus_slint,
    RobotStaticStatus_slint,
    GlobalLogisticsStatus_slint,
    RobotRespawnStatus_slint,
    RobotModuleStatus_slint,
    RuneStatusSync_slint,
    SentryStatusSync_slint,
    DartSelectTargetStatusSync_slint,
    SentryCtrlResult_slint,
} from "referee_data_struct.slint";


export struct ComponentData {
    type: string,
    color: brush,
    rel_width: float,
    rel_height: float,
    rel_x: float,
    rel_y: float,
    opacity: float,
    layer: int,
}







//为了防止回调透传这种情况，使用回调工厂统一管理后端复杂回调
export global Callback_Factory {
    // 全局变量
    in-out property <int> current-resolution-index: 2; // 当前分辨率索引
    in-out property <int> current-index: 0;  //当前页索引
    in-out property <bool> is_fullscreen: false; //当前是否全屏
    in-out property <float> font_size: 16.2; //全局字体大小比例
    in-out property <image> video_frame; //当前视频帧
    in-out property <int> current_component_index: -1; //当前选中组件索引
    in-out property <string> mqtt_ip: "192.168.12.1";
    in-out property <string> mqtt_port: "3333";
    in-out property <string> mqtt_client_id: "RM_Client";
    in-out property <bool> mqtt_connected: false;
    in-out property <string> mqtt_connect_result_text: "未连接";

    // 组件数据模型 (全部使用相对百分比)
    in-out property <[ComponentData]> components: [];

    //后端裁判系统与机器人数据
    in-out property <Pose_slint> current_pose: { roll:0.0, pitch:0.0, yaw:0.0 };
    in-out property <GameStatus_slint> game_status;
    in-out property <GlobalUnitStatus_slint> global_unit_status;
    in-out property <GlobalLogisticsStatus-slint> global_logistics_status;
    in-out property <RobotRespawnStatus-slint> robot_respawn_status;
    in-out property <RobotStaticStatus-slint> robot_static_status;
    in-out property <RobotDynamicStatus-slint> robot_dynamic_status;
    in-out property <RobotModuleStatus-slint> robot_module_status;
    in-out property <RuneStatusSync_slint> rune_status;
    in-out property <SentryStatusSync_slint> sentry_status;
    in-out property <DartSelectTargetStatusSync_slint> dart_select_target_status;
    in-out property <SentryCtrlResult_slint> sentry_ctrl_result;

    //全局回调
    callback open-url(string);
    callback set_resolution(string);
    callback set_fullscreen(bool);
    callback save_to_json();
    callback minimize_window();
    callback maximize_window(bool);
    callback close_window();
    callback move_window(length, length);
    callback apply_mqtt_config(string, string, string) -> bool;
}
