export struct ComponentData {
    type: string,
    color: brush,
    rel_width: float,
    rel_height: float,
    rel_x: float,
    rel_y: float,
    opacity: float,
    layer: int,
}

export struct Pose{
    roll: float,
    pitch: float,
    yaw: float,
}

//为了防止回调透传这种情况，使用回调工厂统一管理后端复杂回调
export global Callback_Factory{
    // 全局变量
    in-out property <int> current-resolution-index: 0; // 当前分辨率索引
    in-out property <int> current-index: 0;  //当前页索引
    in-out property <bool> is_fullscreen: false; //当前是否全屏
    in-out property <float> font_size: 16.2; //全局字体大小比例
    in-out property <image> video_frame; //当前视频帧
    in-out property <int> current_component_index: -1; //当前选中组件索引

    // 组件数据模型 (全部使用相对百分比)


    in-out property <[ComponentData]> components: [];
    in-out property <Pose> current_pose: {roll:0.0, pitch:0.0, yaw:0.0};


    //全局回调
    callback open-url(string);
    callback set_resolution(string);
    callback set_fullscreen(bool);
    

}