import {Callback_Factory} from "callback_factory.slint";
export component Page_About inherits Rectangle {
    callback open_url(string);

    width: 100%;
    height: 100%;
    background: @linear-gradient(180deg, #5c6175 0%, #080114 100%);

    Image {
        source: @image-url("images/phoenix.png");
        image-fit: contain;
        width: 600px;
        height: 400px;
        x: (parent.width - self.width) / 2 -100px; 
        
        // 垂直居中，并向上偏移 60px (为下方的文字留出空间)
        y: (parent.height - self.height) / 2 - 150px; 
    }

    Image{
        source: @image-url("images/R.png");
        image-fit: contain;
        width: 200px;
        height: 200px;
        x: (parent.width - self.width) / 2 + 100px; 
        y: (parent.height - self.height) / 2 - 150px;
    }


    Text { 
        text: "关于 RoboMaster Client v0.1 "; 
        color: area_client.has-hover ? #4da6ff : white;
        font-size: 24px; 
        horizontal-alignment: center;
        vertical-alignment: center;

        area_client := TouchArea {
            width: 100%;
            height: 100%;
            mouse-cursor: pointer; // 鼠标变成手型
            clicked => {
                // 触发回调，传递 URL
                Callback_Factory.open-url("https://github.com/SillyBeee/Robomaster_Phoenix_Custom_Client");
            }
        }
    }

    Text { 
        text: " Made With Slint"; 
        color:  area_slint.has-hover ? #4da6ff : white;
        font-size: 24px; 
        x: (parent.width - self.width) / 2;
        y: (parent.height) / 2 + 60px;
        area_slint := TouchArea {
            width: 100%;
            height: 100%;
            mouse-cursor: pointer; // 鼠标变成手型
            clicked => {
                // 触发回调，传递 URL
                Callback_Factory.open-url("https://slint.dev/");
            }
        }
    }

    Text { 
        text: " Copyright (c) 2025 HDU—PHOENIX "; 
        color:  area_phoenix.has-hover ? #4da6ff : white;
        font-size: 24px; 
        x: (parent.width - self.width) / 2;
        y: (parent.height) / 2 + 20px;
        area_phoenix := TouchArea {
            width: 100%;
            height: 100%;
            mouse-cursor: pointer; // 鼠标变成手型
            clicked => {
                // 触发回调，传递 URL
                Callback_Factory.open-url("https://github.com/HDU-PHOENIX");
            }
        }
    }


    
    
}