import { VerticalBox } from "std-widgets.slint";
import { Page_Setting } from "page_setting.slint";
import { Page_DashBoard } from "page_dashboard.slint";
import { Page_About } from "page_about.slint";
export component TabView inherits Rectangle {
    // 1. 核心属性：控制当前显示第几页
    in property <int> current-index: 0;

    // 页面 0: 仪表盘
    if root.current-index == 0 : Page_DashBoard {}

    // 页面 1: 系统设置
    if root.current-index == 1 : Page_Setting {}

    // 页面 2: 关于
    if root.current-index == 2 : Page_About {}


    

}

