import { VerticalBox } from "std-widgets.slint";
import { Page_Setting } from "page_setting.slint";
import { Page_DashBoard } from "page_dashboard.slint";
import { Page_About } from "page_about.slint";
import { Callback_Factory, Callback-Factory } from "callback_factory.slint";
export component TabView inherits Rectangle {

    // 页面 0: 仪表盘
    if Callback-Factory.current-index == 0 : Page_DashBoard {}

    // 页面 1: 系统设置
    if Callback-Factory.current-index == 1 : Page_Setting {}

    // 页面 2: 关于
    if Callback-Factory.current-index == 2 : Page_About {}
}

