name: ubuntu-22.04-Slint-v1.14.1-build

on:
  push:
    branches:
      - master
    paths:
      - '**'

jobs:
  build:
    runs-on: ubuntu-24.04
            
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies & Build
        run: |
          set -e
          echo
          echo 'starting build process'
          echo

          echo
          echo 'starting installing deps'
          echo
          chmod +x scripts/setup.bash || true
          # 使用 sudo 安装依赖
          sudo bash scripts/setup.bash


          echo
          echo 'starting gen protobuf files'
          echo
          chmod +x scripts/gen_proto.bash || true
          # 使用 sudo 安装依赖
          sudo bash scripts/gen_proto.bash

          rm -rf build
          echo
          echo 'old build files removed'
          echo
          
          mkdir build
          cd build 
          cmake .. 
          make -j$(nproc) # 使用 nproc 自动获取核心数
          echo
          echo 'build completed successfully'
          echo