name: ubuntu-22.04-Slint-v1.14.1-build

on:
  push:
    branches:
      - master
    paths:
      - '**'

jobs:
  build:
    runs-on: [self-hosted, ]
            
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build in Docker container
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/github/repos/Robomaster_Phoenix_Custom_Client" \
            --user "$(id -u):$(id -g)" \
            custom_client_ubuntu2204_slint1.14.1 \
            bash -c "
              set -e
              echo
              echo 'starting build process'
              echo
      
              cd /github/repos/Robomaster_Phoenix_Custom_Client
              echo
              echo 'entered repo directory'
              echo

              echo
              echo 'starting installing deps'
              echo
              chmod +x scripts/setup.bash || true
              sudo bash scripts/setup.bash

              rm -rf build
              echo
              echo 'old build files removed'
              echo
              
              mkdir build
              cd build 
              cmake .. 
              make -j
              echo
              echo 'build completed successfully'
              echo
            "